// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P3AHR.Models.DBModels;

#nullable disable

namespace APIProduct.Migrations
{
    [DbContext(typeof(DBUserManagementContext))]
    partial class DBUserManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("APIProduct.Models.DBModels.DBTables.tbl_user_type", b =>
                {
                    b.Property<Guid>("user_type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("user_type_level")
                        .HasColumnType("int");

                    b.Property<string>("user_type_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("user_type_id");

                    b.ToTable("tbl_user_type");

                    b.HasData(
                        new
                        {
                            user_type_id = new Guid("2382c7f5-f680-40da-a639-ed0638f57c7d"),
                            is_active = true,
                            user_type_level = 0,
                            user_type_name = "System Admin"
                        });
                });

            modelBuilder.Entity("P3AHR.Models.DBModels.DBTables.tbl_user", b =>
                {
                    b.Property<Guid>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("fk_user_type")
                        .HasColumnType("char(36)");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("user_official_email")
                        .HasColumnType("longtext");

                    b.Property<string>("user_password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("user_persaonal_email")
                        .HasColumnType("longtext");

                    b.Property<string>("user_phone_no")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("user_token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("user_id");

                    b.HasIndex("fk_user_type");

                    b.ToTable("tbl_user");

                    b.HasData(
                        new
                        {
                            user_id = new Guid("5638959b-70eb-40f0-8410-0046b1faaad7"),
                            fk_user_type = new Guid("2382c7f5-f680-40da-a639-ed0638f57c7d"),
                            user_name = "Administrator",
                            user_official_email = "admin@enexol.com",
                            user_password = "WZRHGrsBESr8wYFZ9sx0tPURuZgG2lmzyvWpwXPKz8U=",
                            user_phone_no = "",
                            user_token = ""
                        });
                });

            modelBuilder.Entity("P3AHR.Models.DBModels.DBTables.tbl_user", b =>
                {
                    b.HasOne("APIProduct.Models.DBModels.DBTables.tbl_user_type", "user_type")
                        .WithMany("users")
                        .HasForeignKey("fk_user_type")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("user_type");
                });

            modelBuilder.Entity("APIProduct.Models.DBModels.DBTables.tbl_user_type", b =>
                {
                    b.Navigation("users");
                });
#pragma warning restore 612, 618
        }
    }
}
