// <auto-generated />
using System;
using EMO.Models.DBModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EMO.Migrations
{
    [DbContext(typeof(DBUserManagementContext))]
    partial class DBUserManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_agreement", b =>
                {
                    b.Property<Guid>("agreement_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("agreement_description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("agreement_end_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("agreement_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("agreement_start_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("fk_business")
                        .HasColumnType("uuid");

                    b.Property<Guid>("fk_tenant")
                        .HasColumnType("uuid");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("agreement_id");

                    b.HasIndex("fk_business");

                    b.HasIndex("fk_tenant");

                    b.ToTable("tbl_agreement");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_appliance", b =>
                {
                    b.Property<Guid>("appliance_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("allow_optimization_suggestions")
                        .HasColumnType("boolean");

                    b.Property<string>("allowed_shift_end_time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("allowed_shift_start_time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("appliance_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("can_auto_control")
                        .HasColumnType("boolean");

                    b.Property<string>("company_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("fk_utility")
                        .HasColumnType("uuid");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_critical")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_custom")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_default")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_shiftable")
                        .HasColumnType("boolean");

                    b.Property<float>("max_current")
                        .HasColumnType("real");

                    b.Property<float>("max_power")
                        .HasColumnType("real");

                    b.Property<float>("min_current")
                        .HasColumnType("real");

                    b.Property<float>("min_power")
                        .HasColumnType("real");

                    b.Property<int>("minimum_off_duration_minutes")
                        .HasColumnType("integer");

                    b.Property<int>("minimum_on_duration_minutes")
                        .HasColumnType("integer");

                    b.Property<string>("model_number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("normal_operating_hours")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("normal_power_factor")
                        .HasColumnType("real");

                    b.Property<string>("priority_level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("rated_voltage")
                        .HasColumnType("real");

                    b.Property<float>("standby_power")
                        .HasColumnType("real");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("appliance_id");

                    b.HasIndex("fk_utility");

                    b.ToTable("tbl_appliance");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_building", b =>
                {
                    b.Property<Guid>("building_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("building_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("fk_business")
                        .HasColumnType("uuid");

                    b.Property<Guid>("fk_facility")
                        .HasColumnType("uuid");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("building_id");

                    b.HasIndex("fk_business");

                    b.HasIndex("fk_facility");

                    b.ToTable("tbl_building");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_business", b =>
                {
                    b.Property<Guid>("business_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("business_address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("business_contact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("business_email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("business_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("business_id");

                    b.ToTable("tbl_business");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_business_appliance", b =>
                {
                    b.Property<Guid>("business_appliance_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("allow_optimization_suggestions")
                        .HasColumnType("boolean");

                    b.Property<string>("allowed_shift_end_time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("allowed_shift_start_time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("appliance_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("can_auto_control")
                        .HasColumnType("boolean");

                    b.Property<string>("company_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("fk_appliance")
                        .HasColumnType("uuid");

                    b.Property<Guid>("fk_business")
                        .HasColumnType("uuid");

                    b.Property<Guid>("fk_utility")
                        .HasColumnType("uuid");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_critical")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_custom")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_default")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_shiftable")
                        .HasColumnType("boolean");

                    b.Property<float>("max_current")
                        .HasColumnType("real");

                    b.Property<float>("max_power")
                        .HasColumnType("real");

                    b.Property<float>("min_current")
                        .HasColumnType("real");

                    b.Property<float>("min_power")
                        .HasColumnType("real");

                    b.Property<int>("minimum_off_duration_minutes")
                        .HasColumnType("integer");

                    b.Property<int>("minimum_on_duration_minutes")
                        .HasColumnType("integer");

                    b.Property<string>("model_number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("normal_operating_hours")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("normal_power_factor")
                        .HasColumnType("real");

                    b.Property<string>("priority_level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("rated_voltage")
                        .HasColumnType("real");

                    b.Property<float>("standby_power")
                        .HasColumnType("real");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("business_appliance_id");

                    b.HasIndex("fk_appliance");

                    b.HasIndex("fk_business");

                    b.HasIndex("fk_utility");

                    b.ToTable("tbl_business_appliance");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_business_dashboard_setting", b =>
                {
                    b.Property<Guid>("business_dashboard_setting_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("day_of_week")
                        .HasColumnType("integer");

                    b.Property<Guid>("fk_business")
                        .HasColumnType("uuid");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("off_peak_tariff_rate")
                        .HasColumnType("numeric");

                    b.Property<int>("online_sensor_threshold_seconds")
                        .HasColumnType("integer");

                    b.Property<string>("peak_end_time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("peak_start_time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("peak_tariff_rate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("tariff_rate")
                        .HasColumnType("numeric");

                    b.Property<string>("timezone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("business_dashboard_setting_id");

                    b.ToTable("tbl_business_dashboard_setting");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_contact_person", b =>
                {
                    b.Property<Guid>("contact_person_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("contact_person_email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("contact_person_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("contact_person_phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("fk_agreement")
                        .HasColumnType("uuid");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.HasKey("contact_person_id");

                    b.HasIndex("fk_agreement");

                    b.ToTable("tbl_contact_person");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_dashboard_aggregate", b =>
                {
                    b.Property<Guid>("dashboard_aggregate_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("current_load_w")
                        .HasColumnType("double precision");

                    b.Property<double>("estimated_cost")
                        .HasColumnType("double precision");

                    b.Property<Guid>("fk_business")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("fk_office")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("fk_tenant")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("from_time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("granularity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("offpeak_kwh")
                        .HasColumnType("double precision");

                    b.Property<int>("online_sensors")
                        .HasColumnType("integer");

                    b.Property<double>("peak_demand_w")
                        .HasColumnType("double precision");

                    b.Property<double>("peak_kwh")
                        .HasColumnType("double precision");

                    b.Property<double>("saving_opportunity")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("to_time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("total_energy_kwh")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("dashboard_aggregate_id");

                    b.ToTable("tbl_dashboard_aggregate");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_dashboard_chart_aggregate", b =>
                {
                    b.Property<Guid>("dashboard_chart_aggregate_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("chart_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("fk_business")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("fk_tenant")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("from_time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("payload_json")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("range_key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("scope_id")
                        .HasColumnType("uuid");

                    b.Property<string>("scope_level")
                        .HasColumnType("text");

                    b.Property<DateTime>("to_time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("dashboard_chart_aggregate_id");

                    b.HasIndex("scope_level", "scope_id", "chart_type", "range_key")
                        .IsUnique()
                        .HasDatabaseName("UX_dashboard_chart_scope");

                    b.ToTable("tbl_dashboard_chart_aggregate");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_dashboard_suggestion", b =>
                {
                    b.Property<Guid>("dashboard_suggestion_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("affected_appliance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("affected_office")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("affected_utility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("can_apply_action")
                        .HasColumnType("boolean");

                    b.Property<string>("confidence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("conflicts_with_peak_hour")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("estimated_saving_cost")
                        .HasColumnType("double precision");

                    b.Property<double?>("estimated_saving_kwh")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("fk_appliance")
                        .HasColumnType("uuid");

                    b.Property<Guid>("fk_business")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("fk_office")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("fk_sensor")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("fk_tenant")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("from_time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("reason_code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("recommendation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("to_time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("dashboard_suggestion_id");

                    b.ToTable("tbl_dashboard_suggestion");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_demand_management_setting", b =>
                {
                    b.Property<Guid>("demand_management_setting_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("demand_interval_minutes")
                        .HasColumnType("integer");

                    b.Property<decimal>("demand_limit_kw")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("monthly_energy_target_kwh")
                        .HasColumnType("numeric");

                    b.Property<bool>("enable_demand_threshold_control")
                        .HasColumnType("boolean");

                    b.Property<bool>("enable_peak_hour_control")
                        .HasColumnType("boolean");

                    b.Property<Guid>("fk_business")
                        .HasColumnType("uuid");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("recovery_threshold_kw")
                        .HasColumnType("numeric");

                    b.Property<int>("stabilization_minutes")
                        .HasColumnType("integer");

                    b.Property<bool>("suggestion_only_mode")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("warning_threshold_percent")
                        .HasColumnType("numeric");

                    b.HasKey("demand_management_setting_id");

                    b.ToTable("tbl_demand_management_setting");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_device", b =>
                {
                    b.Property<Guid>("device_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("device_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("fk_business")
                        .HasColumnType("uuid");

                    b.Property<Guid>("fk_office")
                        .HasColumnType("uuid");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("mac_address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("device_id");

                    b.HasIndex("fk_business");

                    b.HasIndex("fk_office");

                    b.ToTable("tbl_device");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_energy_tariff_plan", b =>
                {
                    b.Property<Guid>("energy_tariff_plan_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("demand_charge_per_kw")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("effective_from")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("effective_to")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("fk_business")
                        .HasColumnType("uuid");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("off_peak_rate_per_kwh")
                        .HasColumnType("numeric");

                    b.Property<decimal>("peak_rate_per_kwh")
                        .HasColumnType("numeric");

                    b.Property<string>("plan_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("standard_rate_per_kwh")
                        .HasColumnType("numeric");

                    b.Property<string>("timezone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("energy_tariff_plan_id");

                    b.ToTable("tbl_energy_tariff_plan");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_facility", b =>
                {
                    b.Property<Guid>("facility_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("facility_address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("facility_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("fk_business")
                        .HasColumnType("uuid");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("facility_id");

                    b.HasIndex("fk_business");

                    b.ToTable("tbl_facility");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_floor", b =>
                {
                    b.Property<Guid>("floor_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("fk_building")
                        .HasColumnType("uuid");

                    b.Property<Guid>("fk_business")
                        .HasColumnType("uuid");

                    b.Property<string>("floor_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("floor_no")
                        .HasColumnType("integer");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("floor_id");

                    b.HasIndex("fk_building");

                    b.HasIndex("fk_business");

                    b.ToTable("tbl_floor");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_gender", b =>
                {
                    b.Property<Guid>("gender_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("gender_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.HasKey("gender_id");

                    b.ToTable("tbl_gender");

                    b.HasData(
                        new
                        {
                            gender_id = new Guid("96bc4a62-b472-48dd-af36-65381ab71810"),
                            gender_name = "Male",
                            is_deleted = false
                        },
                        new
                        {
                            gender_id = new Guid("b6c32b3d-8823-4fc7-9248-c5daa2a53896"),
                            gender_name = "Female",
                            is_deleted = false
                        },
                        new
                        {
                            gender_id = new Guid("ee218df5-1dd7-4c96-993c-98361446145a"),
                            gender_name = "Prefer not to say",
                            is_deleted = false
                        },
                        new
                        {
                            gender_id = new Guid("b20f4954-9409-4fa6-890f-fefd8d169818"),
                            gender_name = "Other",
                            is_deleted = false
                        });
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_hvac_loop_setting", b =>
                {
                    b.Property<Guid>("hvac_loop_setting_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("fk_sensor")
                        .HasColumnType("uuid");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("loop_enabled")
                        .HasColumnType("boolean");

                    b.Property<int>("loop_off_seconds")
                        .HasColumnType("integer");

                    b.Property<int>("loop_on_seconds")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("loop_started_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("hvac_loop_setting_id");

                    b.HasIndex("fk_sensor");

                    b.ToTable("tbl_hvac_loop_setting");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_office", b =>
                {
                    b.Property<Guid>("office_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("after_hours_alert_enabled")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly>("closing_time")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("fk_business")
                        .HasColumnType("uuid");

                    b.Property<Guid>("fk_section")
                        .HasColumnType("uuid");

                    b.Property<bool>("is_24_hours")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_occupied")
                        .HasColumnType("boolean");

                    b.Property<string>("office_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("opening_time")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("working_days")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("office_id");

                    b.HasIndex("fk_business");

                    b.HasIndex("fk_section");

                    b.ToTable("tbl_office");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_office_agreement", b =>
                {
                    b.Property<Guid>("office_agreement_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("fk_agreement")
                        .HasColumnType("uuid");

                    b.Property<Guid>("fk_office")
                        .HasColumnType("uuid");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.HasKey("office_agreement_id");

                    b.HasIndex("fk_agreement");

                    b.HasIndex("fk_office");

                    b.ToTable("tbl_office_agreement");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_section", b =>
                {
                    b.Property<Guid>("section_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("fk_business")
                        .HasColumnType("uuid");

                    b.Property<Guid>("fk_floor")
                        .HasColumnType("uuid");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("section_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("section_id");

                    b.HasIndex("fk_business");

                    b.HasIndex("fk_floor");

                    b.ToTable("tbl_section");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_sensor", b =>
                {
                    b.Property<Guid>("sensor_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("fk_device")
                        .HasColumnType("uuid");

                    b.Property<Guid>("fk_utility")
                        .HasColumnType("uuid");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("meter_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sensor_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("serial_address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("standby_auto_off")
                        .HasColumnType("boolean");

                    b.HasKey("sensor_id");

                    b.HasIndex("fk_device");

                    b.HasIndex("fk_utility");

                    b.ToTable("tbl_sensor");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_sensor_appliance", b =>
                {
                    b.Property<Guid>("sensor_appliance_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("assigned_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("fk_appliance")
                        .HasColumnType("uuid");

                    b.Property<Guid>("fk_sensor")
                        .HasColumnType("uuid");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("sensor_appliance_id");

                    b.HasIndex("fk_appliance");

                    b.HasIndex("fk_sensor");

                    b.ToTable("tbl_sensor_appliance");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_singal_phase_data", b =>
                {
                    b.Property<Guid>("singal_phase_data_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("active_energy")
                        .HasColumnType("real");

                    b.Property<float>("active_power")
                        .HasColumnType("real");

                    b.Property<float>("apperent_power")
                        .HasColumnType("real");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("current")
                        .HasColumnType("real");

                    b.Property<int>("epoch_sec")
                        .HasColumnType("integer");

                    b.Property<Guid>("fk_sensor")
                        .HasColumnType("uuid");

                    b.Property<float>("frequency")
                        .HasColumnType("real");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<int>("packet_id")
                        .HasColumnType("integer");

                    b.Property<float>("power_factor")
                        .HasColumnType("real");

                    b.Property<float>("reactive_energy")
                        .HasColumnType("real");

                    b.Property<float>("reactive_power")
                        .HasColumnType("real");

                    b.Property<float>("volt")
                        .HasColumnType("real");

                    b.HasKey("singal_phase_data_id");

                    b.HasIndex("fk_sensor");

                    b.HasIndex("fk_sensor", "created_at")
                        .HasDatabaseName("IX_signal_phase_sensor_created_at");

                    b.ToTable("tbl_singal_phase_data");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_sub_user_type", b =>
                {
                    b.Property<Guid>("sub_user_type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("fk_user_type")
                        .HasColumnType("uuid");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<int>("sub_user_type_level")
                        .HasColumnType("integer");

                    b.Property<string>("sub_user_type_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("sub_user_type_id");

                    b.HasIndex("fk_user_type");

                    b.ToTable("tbl_sub_user_type");

                    b.HasData(
                        new
                        {
                            sub_user_type_id = new Guid("bbb16965-7fc1-405a-b85d-8dae8276aefd"),
                            fk_user_type = new Guid("6e8bd2db-2a86-4fb3-9c5b-7595dcb6e373"),
                            is_active = true,
                            is_deleted = false,
                            sub_user_type_level = 0,
                            sub_user_type_name = "Root"
                        },
                        new
                        {
                            sub_user_type_id = new Guid("b2511b9a-9d60-488b-b5f2-37208fceadbd"),
                            fk_user_type = new Guid("6e8bd2db-2a86-4fb3-9c5b-7595dcb6e373"),
                            is_active = true,
                            is_deleted = false,
                            sub_user_type_level = 1,
                            sub_user_type_name = "Manager"
                        },
                        new
                        {
                            sub_user_type_id = new Guid("184bc355-6140-433d-b0c8-7f630e76c504"),
                            fk_user_type = new Guid("d4e0ef5f-35af-4ec7-9c06-c96295402e6c"),
                            is_active = true,
                            is_deleted = false,
                            sub_user_type_level = 0,
                            sub_user_type_name = "Root"
                        },
                        new
                        {
                            sub_user_type_id = new Guid("eddde854-d3fb-4c60-8193-b845bad4e2eb"),
                            fk_user_type = new Guid("d4e0ef5f-35af-4ec7-9c06-c96295402e6c"),
                            is_active = true,
                            is_deleted = false,
                            sub_user_type_level = 1,
                            sub_user_type_name = "Manager"
                        },
                        new
                        {
                            sub_user_type_id = new Guid("5cd35666-f9a5-49c6-83d9-dbb078e83787"),
                            fk_user_type = new Guid("c247b2d2-9635-4ceb-ab16-f4e1453bf6f1"),
                            is_active = true,
                            is_deleted = false,
                            sub_user_type_level = 0,
                            sub_user_type_name = "Root"
                        });
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_tariff_time_period", b =>
                {
                    b.Property<Guid>("tariff_time_period_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("day_of_week")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("end_time")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("fk_tariff_plan")
                        .HasColumnType("uuid");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("period_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("period_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("season_end")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("season_start")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("start_time")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("tariff_time_period_id");

                    b.ToTable("tbl_tariff_time_period");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_user", b =>
                {
                    b.Property<Guid>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("fk_business")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("fk_gender")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("fk_handler")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("fk_sub_user_type")
                        .HasColumnType("uuid");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("last_activity_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("otp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("tbl_user_typeuser_type_id")
                        .HasColumnType("uuid");

                    b.Property<string>("user_email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("user_password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("user_phone_no")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("user_token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("user_id");

                    b.HasIndex("fk_business");

                    b.HasIndex("fk_gender");

                    b.HasIndex("fk_handler");

                    b.HasIndex("fk_sub_user_type");

                    b.HasIndex("tbl_user_typeuser_type_id");

                    b.ToTable("tbl_user");

                    b.HasData(
                        new
                        {
                            user_id = new Guid("7452b4ab-dad1-42ef-ae10-5d58a5743824"),
                            fk_gender = new Guid("ee218df5-1dd7-4c96-993c-98361446145a"),
                            fk_sub_user_type = new Guid("bbb16965-7fc1-405a-b85d-8dae8276aefd"),
                            is_active = true,
                            is_deleted = false,
                            name = "Administrator",
                            otp = "",
                            user_email = "",
                            user_name = "admin@emo.com",
                            user_password = "WZRHGrsBESr8wYFZ9sx0tPURuZgG2lmzyvWpwXPKz8U=",
                            user_phone_no = "",
                            user_token = ""
                        });
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_user_image", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("fk_user")
                        .HasColumnType("uuid");

                    b.Property<string>("imageBase64")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.HasKey("id");

                    b.HasIndex("fk_user")
                        .IsUnique();

                    b.ToTable("tbl_user_image");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_user_type", b =>
                {
                    b.Property<Guid>("user_type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<int>("user_type_level")
                        .HasColumnType("integer");

                    b.Property<string>("user_type_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("user_type_id");

                    b.ToTable("tbl_user_type");

                    b.HasData(
                        new
                        {
                            user_type_id = new Guid("6e8bd2db-2a86-4fb3-9c5b-7595dcb6e373"),
                            is_active = true,
                            is_deleted = false,
                            user_type_level = 0,
                            user_type_name = "System Admin"
                        },
                        new
                        {
                            user_type_id = new Guid("d4e0ef5f-35af-4ec7-9c06-c96295402e6c"),
                            is_active = true,
                            is_deleted = false,
                            user_type_level = 1,
                            user_type_name = "Business Admin"
                        },
                        new
                        {
                            user_type_id = new Guid("c247b2d2-9635-4ceb-ab16-f4e1453bf6f1"),
                            is_active = true,
                            is_deleted = false,
                            user_type_level = 2,
                            user_type_name = "Tenant"
                        });
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_utility", b =>
                {
                    b.Property<Guid>("utility_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("utility_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("utility_id");

                    b.ToTable("tbl_utility");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_agreement", b =>
                {
                    b.HasOne("EMO.Models.DBModels.DBTables.tbl_business", "business")
                        .WithMany("agreements")
                        .HasForeignKey("fk_business")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EMO.Models.DBModels.DBTables.tbl_user", "tenant")
                        .WithMany("agreements")
                        .HasForeignKey("fk_tenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("business");

                    b.Navigation("tenant");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_appliance", b =>
                {
                    b.HasOne("EMO.Models.DBModels.DBTables.tbl_utility", "utility")
                        .WithMany("appliances")
                        .HasForeignKey("fk_utility")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("utility");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_building", b =>
                {
                    b.HasOne("EMO.Models.DBModels.DBTables.tbl_business", "business")
                        .WithMany("buildings")
                        .HasForeignKey("fk_business")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EMO.Models.DBModels.DBTables.tbl_facility", "facility")
                        .WithMany("buildings")
                        .HasForeignKey("fk_facility")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("business");

                    b.Navigation("facility");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_business_appliance", b =>
                {
                    b.HasOne("EMO.Models.DBModels.DBTables.tbl_appliance", "default_appliance")
                        .WithMany("business_appliances")
                        .HasForeignKey("fk_appliance")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EMO.Models.DBModels.DBTables.tbl_business", "business")
                        .WithMany("business_appliances")
                        .HasForeignKey("fk_business")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EMO.Models.DBModels.DBTables.tbl_utility", "utility")
                        .WithMany("business_appliances")
                        .HasForeignKey("fk_utility")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("business");

                    b.Navigation("default_appliance");

                    b.Navigation("utility");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_contact_person", b =>
                {
                    b.HasOne("EMO.Models.DBModels.DBTables.tbl_agreement", "agreement")
                        .WithMany("contact_persons")
                        .HasForeignKey("fk_agreement")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("agreement");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_device", b =>
                {
                    b.HasOne("EMO.Models.DBModels.DBTables.tbl_business", "business")
                        .WithMany("devices")
                        .HasForeignKey("fk_business")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EMO.Models.DBModels.DBTables.tbl_office", "office")
                        .WithMany("devices")
                        .HasForeignKey("fk_office")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("business");

                    b.Navigation("office");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_facility", b =>
                {
                    b.HasOne("EMO.Models.DBModels.DBTables.tbl_business", "business")
                        .WithMany("facilities")
                        .HasForeignKey("fk_business")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("business");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_floor", b =>
                {
                    b.HasOne("EMO.Models.DBModels.DBTables.tbl_building", "building")
                        .WithMany("floors")
                        .HasForeignKey("fk_building")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EMO.Models.DBModels.DBTables.tbl_business", "business")
                        .WithMany("floors")
                        .HasForeignKey("fk_business")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("building");

                    b.Navigation("business");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_hvac_loop_setting", b =>
                {
                    b.HasOne("EMO.Models.DBModels.DBTables.tbl_sensor", "sensor")
                        .WithMany("hvac_loop_settings")
                        .HasForeignKey("fk_sensor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("sensor");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_office", b =>
                {
                    b.HasOne("EMO.Models.DBModels.DBTables.tbl_business", "business")
                        .WithMany("offices")
                        .HasForeignKey("fk_business")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EMO.Models.DBModels.DBTables.tbl_section", "section")
                        .WithMany("offices")
                        .HasForeignKey("fk_section")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("business");

                    b.Navigation("section");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_office_agreement", b =>
                {
                    b.HasOne("EMO.Models.DBModels.DBTables.tbl_agreement", "agreement")
                        .WithMany("office_agreement")
                        .HasForeignKey("fk_agreement")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EMO.Models.DBModels.DBTables.tbl_office", "office")
                        .WithMany("office_agreement")
                        .HasForeignKey("fk_office")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("agreement");

                    b.Navigation("office");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_section", b =>
                {
                    b.HasOne("EMO.Models.DBModels.DBTables.tbl_business", "business")
                        .WithMany("sections")
                        .HasForeignKey("fk_business")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EMO.Models.DBModels.DBTables.tbl_floor", "floor")
                        .WithMany("sections")
                        .HasForeignKey("fk_floor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("business");

                    b.Navigation("floor");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_sensor", b =>
                {
                    b.HasOne("EMO.Models.DBModels.DBTables.tbl_device", "device")
                        .WithMany("sensors")
                        .HasForeignKey("fk_device")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EMO.Models.DBModels.DBTables.tbl_utility", "utility")
                        .WithMany("sensors")
                        .HasForeignKey("fk_utility")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("device");

                    b.Navigation("utility");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_sensor_appliance", b =>
                {
                    b.HasOne("EMO.Models.DBModels.DBTables.tbl_business_appliance", "appliance")
                        .WithMany("sensor_appliances")
                        .HasForeignKey("fk_appliance")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EMO.Models.DBModels.DBTables.tbl_sensor", "sensor")
                        .WithMany("sensor_appliances")
                        .HasForeignKey("fk_sensor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("appliance");

                    b.Navigation("sensor");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_singal_phase_data", b =>
                {
                    b.HasOne("EMO.Models.DBModels.DBTables.tbl_sensor", "sensor")
                        .WithMany("singal_phase_data")
                        .HasForeignKey("fk_sensor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("sensor");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_sub_user_type", b =>
                {
                    b.HasOne("EMO.Models.DBModels.DBTables.tbl_user_type", "user_type")
                        .WithMany("subuser_types")
                        .HasForeignKey("fk_user_type")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("user_type");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_user", b =>
                {
                    b.HasOne("EMO.Models.DBModels.DBTables.tbl_business", "businesses")
                        .WithMany("users")
                        .HasForeignKey("fk_business")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EMO.Models.DBModels.DBTables.tbl_gender", "gender")
                        .WithMany("users")
                        .HasForeignKey("fk_gender")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EMO.Models.DBModels.DBTables.tbl_user", "handler")
                        .WithMany("users")
                        .HasForeignKey("fk_handler")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EMO.Models.DBModels.DBTables.tbl_sub_user_type", "sub_user_type")
                        .WithMany("users")
                        .HasForeignKey("fk_sub_user_type")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EMO.Models.DBModels.DBTables.tbl_user_type", null)
                        .WithMany("users")
                        .HasForeignKey("tbl_user_typeuser_type_id");

                    b.Navigation("businesses");

                    b.Navigation("gender");

                    b.Navigation("handler");

                    b.Navigation("sub_user_type");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_user_image", b =>
                {
                    b.HasOne("EMO.Models.DBModels.DBTables.tbl_user", "user")
                        .WithOne("user_image")
                        .HasForeignKey("EMO.Models.DBModels.DBTables.tbl_user_image", "fk_user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_agreement", b =>
                {
                    b.Navigation("contact_persons");

                    b.Navigation("office_agreement");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_appliance", b =>
                {
                    b.Navigation("business_appliances");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_building", b =>
                {
                    b.Navigation("floors");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_business", b =>
                {
                    b.Navigation("agreements");

                    b.Navigation("buildings");

                    b.Navigation("business_appliances");

                    b.Navigation("devices");

                    b.Navigation("facilities");

                    b.Navigation("floors");

                    b.Navigation("offices");

                    b.Navigation("sections");

                    b.Navigation("users");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_business_appliance", b =>
                {
                    b.Navigation("sensor_appliances");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_device", b =>
                {
                    b.Navigation("sensors");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_facility", b =>
                {
                    b.Navigation("buildings");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_floor", b =>
                {
                    b.Navigation("sections");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_gender", b =>
                {
                    b.Navigation("users");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_office", b =>
                {
                    b.Navigation("devices");

                    b.Navigation("office_agreement");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_section", b =>
                {
                    b.Navigation("offices");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_sensor", b =>
                {
                    b.Navigation("hvac_loop_settings");

                    b.Navigation("sensor_appliances");

                    b.Navigation("singal_phase_data");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_sub_user_type", b =>
                {
                    b.Navigation("users");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_user", b =>
                {
                    b.Navigation("agreements");

                    b.Navigation("user_image")
                        .IsRequired();

                    b.Navigation("users");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_user_type", b =>
                {
                    b.Navigation("subuser_types");

                    b.Navigation("users");
                });

            modelBuilder.Entity("EMO.Models.DBModels.DBTables.tbl_utility", b =>
                {
                    b.Navigation("appliances");

                    b.Navigation("business_appliances");

                    b.Navigation("sensors");
                });
#pragma warning restore 612, 618
        }
    }
}
