using AutoMapper;
using EMO.Extensions;
using EMO.Models.DBModels.DBTables;
using EMO.Models.DTOs.ApplianceDTOs;

namespace EMO.Extensions.AutoMapper
{
    public class ApplianceMapper : Profile
    {
        private readonly OtherServices otherServices = new();

        public ApplianceMapper()
        {
            CreateMap<AddApplianceDTO, tbl_appliance>()
                .ForMember(d => d.appliance_name, opt => opt.MapFrom(src => src.applianceName))
                .ForMember(d => d.company_name, opt => opt.MapFrom(src => src.companyName))
                .ForMember(d => d.model_number, opt => opt.MapFrom(src => src.modelNumber))
                .ForMember(d => d.rated_voltage, opt => opt.MapFrom(src => src.ratedVoltage))
                .ForMember(d => d.min_current, opt => opt.MapFrom(src => src.minCurrent))
                .ForMember(d => d.max_current, opt => opt.MapFrom(src => src.maxCurrent))
                .ForMember(d => d.min_power, opt => opt.MapFrom(src => src.minPower))
                .ForMember(d => d.max_power, opt => opt.MapFrom(src => src.maxPower))
                .ForMember(d => d.standby_power, opt => opt.MapFrom(src => src.standbyPower))
                .ForMember(d => d.normal_power_factor, opt => opt.MapFrom(src => src.normalPowerFactor))
                .ForMember(d => d.description, opt => opt.MapFrom(src => src.description))
                .ForMember(d => d.priority_level, opt => opt.MapFrom(src => src.priorityLevel))
                .ForMember(d => d.is_critical, opt => opt.MapFrom(src => src.isCritical))
                .ForMember(d => d.is_default, opt => opt.MapFrom(src => src.isDefault))
                .ForMember(d => d.is_custom, opt => opt.MapFrom(src => src.isCustom))
                .ForMember(d => d.is_active, opt => opt.MapFrom(src => src.isActive))
                .ForMember(d => d.fk_utility, opt => opt.MapFrom(src => Guid.Parse(src.fkUtility)));

            CreateMap<UpdateApplianceDTO, tbl_appliance>()
                .ForMember(d => d.appliance_name, opt => opt.MapFrom((src, dest) => otherServices.Check(src.applianceName) ? src.applianceName : dest.appliance_name))
                .ForMember(d => d.company_name, opt => opt.MapFrom((src, dest) => otherServices.Check(src.companyName) ? src.companyName : dest.company_name))
                .ForMember(d => d.model_number, opt => opt.MapFrom((src, dest) => otherServices.Check(src.modelNumber) ? src.modelNumber : dest.model_number))
                .ForMember(d => d.rated_voltage, opt => opt.MapFrom(src => src.ratedVoltage))
                .ForMember(d => d.min_current, opt => opt.MapFrom(src => src.minCurrent))
                .ForMember(d => d.max_current, opt => opt.MapFrom(src => src.maxCurrent))
                .ForMember(d => d.min_power, opt => opt.MapFrom(src => src.minPower))
                .ForMember(d => d.max_power, opt => opt.MapFrom(src => src.maxPower))
                .ForMember(d => d.standby_power, opt => opt.MapFrom(src => src.standbyPower))
                .ForMember(d => d.normal_power_factor, opt => opt.MapFrom(src => src.normalPowerFactor))
                .ForMember(d => d.description, opt => opt.MapFrom((src, dest) => otherServices.Check(src.description) ? src.description : dest.description))
                .ForMember(d => d.priority_level, opt => opt.MapFrom((src, dest) => otherServices.Check(src.priorityLevel) ? src.priorityLevel : dest.priority_level))
                .ForMember(d => d.is_critical, opt => opt.MapFrom(src => src.isCritical))
                .ForMember(d => d.is_default, opt => opt.MapFrom(src => src.isDefault))
                .ForMember(d => d.is_custom, opt => opt.MapFrom(src => src.isCustom))
                .ForMember(d => d.is_active, opt => opt.MapFrom(src => src.isActive))
                .ForMember(d => d.fk_utility, opt => opt.MapFrom((src, dest) => otherServices.Check(src.fkUtility) ? Guid.Parse(src.fkUtility) : dest.fk_utility))
                .ForMember(d => d.updated_at, opt => opt.MapFrom(src => DateTime.Now));

            CreateMap<tbl_appliance, ApplianceResponseDTO>()
                .ForMember(d => d.applianceId, opt => opt.MapFrom(src => src.appliance_id.ToString()))
                .ForMember(d => d.applianceName, opt => opt.MapFrom(src => src.appliance_name))
                .ForMember(d => d.companyName, opt => opt.MapFrom(src => src.company_name))
                .ForMember(d => d.modelNumber, opt => opt.MapFrom(src => src.model_number))
                .ForMember(d => d.ratedVoltage, opt => opt.MapFrom(src => src.rated_voltage))
                .ForMember(d => d.minCurrent, opt => opt.MapFrom(src => src.min_current))
                .ForMember(d => d.maxCurrent, opt => opt.MapFrom(src => src.max_current))
                .ForMember(d => d.minPower, opt => opt.MapFrom(src => src.min_power))
                .ForMember(d => d.maxPower, opt => opt.MapFrom(src => src.max_power))
                .ForMember(d => d.standbyPower, opt => opt.MapFrom(src => src.standby_power))
                .ForMember(d => d.normalPowerFactor, opt => opt.MapFrom(src => src.normal_power_factor))
                .ForMember(d => d.description, opt => opt.MapFrom(src => src.description))
                .ForMember(d => d.priorityLevel, opt => opt.MapFrom(src => src.priority_level))
                .ForMember(d => d.isCritical, opt => opt.MapFrom(src => src.is_critical))
                .ForMember(d => d.isDefault, opt => opt.MapFrom(src => src.is_default))
                .ForMember(d => d.isCustom, opt => opt.MapFrom(src => src.is_custom))
                .ForMember(d => d.fkUtility, opt => opt.MapFrom(src => src.fk_utility.ToString()))
                .ForMember(d => d.utilityName, opt => opt.MapFrom(src => src.utility.utility_name))
                .ForMember(d => d.createdAt, opt => opt.MapFrom(src => src.created_at.ToString("yyyy-MM-dd HH:mm:ss")))
                .ForMember(d => d.updatedAt, opt => opt.MapFrom(src => src.updated_at.ToString("yyyy-MM-dd HH:mm:ss")))
                .ForMember(d => d.isActive, opt => opt.MapFrom(src => src.is_active));

            CreateMap<AddApplianceDTO, tbl_business_appliance>()
                .ForMember(d => d.fk_business, opt => opt.MapFrom(src => Guid.Parse(src.fkBusiness)))
                .ForMember(d => d.appliance_name, opt => opt.MapFrom(src => src.applianceName))
                .ForMember(d => d.company_name, opt => opt.MapFrom(src => src.companyName))
                .ForMember(d => d.model_number, opt => opt.MapFrom(src => src.modelNumber))
                .ForMember(d => d.rated_voltage, opt => opt.MapFrom(src => src.ratedVoltage))
                .ForMember(d => d.min_current, opt => opt.MapFrom(src => src.minCurrent))
                .ForMember(d => d.max_current, opt => opt.MapFrom(src => src.maxCurrent))
                .ForMember(d => d.min_power, opt => opt.MapFrom(src => src.minPower))
                .ForMember(d => d.max_power, opt => opt.MapFrom(src => src.maxPower))
                .ForMember(d => d.standby_power, opt => opt.MapFrom(src => src.standbyPower))
                .ForMember(d => d.normal_power_factor, opt => opt.MapFrom(src => src.normalPowerFactor))
                .ForMember(d => d.description, opt => opt.MapFrom(src => src.description))
                .ForMember(d => d.priority_level, opt => opt.MapFrom(src => src.priorityLevel))
                .ForMember(d => d.is_critical, opt => opt.MapFrom(src => src.isCritical))
                .ForMember(d => d.is_default, opt => opt.MapFrom(src => false))
                .ForMember(d => d.is_custom, opt => opt.MapFrom(src => true))
                .ForMember(d => d.is_active, opt => opt.MapFrom(src => src.isActive))
                .ForMember(d => d.fk_utility, opt => opt.MapFrom(src => Guid.Parse(src.fkUtility)));

            CreateMap<UpdateApplianceDTO, tbl_business_appliance>()
                .ForMember(d => d.appliance_name, opt => opt.MapFrom((src, dest) => otherServices.Check(src.applianceName) ? src.applianceName : dest.appliance_name))
                .ForMember(d => d.company_name, opt => opt.MapFrom((src, dest) => otherServices.Check(src.companyName) ? src.companyName : dest.company_name))
                .ForMember(d => d.model_number, opt => opt.MapFrom((src, dest) => otherServices.Check(src.modelNumber) ? src.modelNumber : dest.model_number))
                .ForMember(d => d.rated_voltage, opt => opt.MapFrom(src => src.ratedVoltage))
                .ForMember(d => d.min_current, opt => opt.MapFrom(src => src.minCurrent))
                .ForMember(d => d.max_current, opt => opt.MapFrom(src => src.maxCurrent))
                .ForMember(d => d.min_power, opt => opt.MapFrom(src => src.minPower))
                .ForMember(d => d.max_power, opt => opt.MapFrom(src => src.maxPower))
                .ForMember(d => d.standby_power, opt => opt.MapFrom(src => src.standbyPower))
                .ForMember(d => d.normal_power_factor, opt => opt.MapFrom(src => src.normalPowerFactor))
                .ForMember(d => d.description, opt => opt.MapFrom((src, dest) => otherServices.Check(src.description) ? src.description : dest.description))
                .ForMember(d => d.priority_level, opt => opt.MapFrom((src, dest) => otherServices.Check(src.priorityLevel) ? src.priorityLevel : dest.priority_level))
                .ForMember(d => d.is_critical, opt => opt.MapFrom(src => src.isCritical))
                .ForMember(d => d.is_default, opt => opt.MapFrom(src => src.isDefault))
                .ForMember(d => d.is_custom, opt => opt.MapFrom(src => src.isCustom))
                .ForMember(d => d.is_active, opt => opt.MapFrom(src => src.isActive))
                .ForMember(d => d.fk_utility, opt => opt.MapFrom((src, dest) => otherServices.Check(src.fkUtility) ? Guid.Parse(src.fkUtility) : dest.fk_utility))
                .ForMember(d => d.updated_at, opt => opt.MapFrom(src => DateTime.Now));

            CreateMap<tbl_business_appliance, ApplianceResponseDTO>()
                .ForMember(d => d.applianceId, opt => opt.MapFrom(src => src.business_appliance_id.ToString()))
                .ForMember(d => d.applianceName, opt => opt.MapFrom(src => src.appliance_name))
                .ForMember(d => d.companyName, opt => opt.MapFrom(src => src.company_name))
                .ForMember(d => d.modelNumber, opt => opt.MapFrom(src => src.model_number))
                .ForMember(d => d.fkBusiness, opt => opt.MapFrom(src => src.fk_business.ToString()))
                .ForMember(d => d.businessName, opt => opt.MapFrom(src => src.business.business_name))
                .ForMember(d => d.fkDefaultAppliance, opt => opt.MapFrom(src => src.fk_appliance.HasValue ? src.fk_appliance.Value.ToString() : string.Empty))
                .ForMember(d => d.ratedVoltage, opt => opt.MapFrom(src => src.rated_voltage))
                .ForMember(d => d.minCurrent, opt => opt.MapFrom(src => src.min_current))
                .ForMember(d => d.maxCurrent, opt => opt.MapFrom(src => src.max_current))
                .ForMember(d => d.minPower, opt => opt.MapFrom(src => src.min_power))
                .ForMember(d => d.maxPower, opt => opt.MapFrom(src => src.max_power))
                .ForMember(d => d.standbyPower, opt => opt.MapFrom(src => src.standby_power))
                .ForMember(d => d.normalPowerFactor, opt => opt.MapFrom(src => src.normal_power_factor))
                .ForMember(d => d.description, opt => opt.MapFrom(src => src.description))
                .ForMember(d => d.priorityLevel, opt => opt.MapFrom(src => src.priority_level))
                .ForMember(d => d.isCritical, opt => opt.MapFrom(src => src.is_critical))
                .ForMember(d => d.isDefault, opt => opt.MapFrom(src => src.is_default))
                .ForMember(d => d.isCustom, opt => opt.MapFrom(src => src.is_custom))
                .ForMember(d => d.fkUtility, opt => opt.MapFrom(src => src.fk_utility.ToString()))
                .ForMember(d => d.utilityName, opt => opt.MapFrom(src => src.utility.utility_name))
                .ForMember(d => d.createdAt, opt => opt.MapFrom(src => src.created_at.ToString("yyyy-MM-dd HH:mm:ss")))
                .ForMember(d => d.updatedAt, opt => opt.MapFrom(src => src.updated_at.ToString("yyyy-MM-dd HH:mm:ss")))
                .ForMember(d => d.isActive, opt => opt.MapFrom(src => src.is_active));
        }
    }
}
